import type { V3LocaleCopy } from './types';

/**
 * Korean copy for the v3 pages. Terminology follows the Shotera app's ko
 * language pack.
 */
export default {
  home: 'Shotera — 더 빠르고 스마트한 스크린샷과 화면 녹화',
  nav: {
    features: '기능',
    versions: '버전 비교',
    changelog: '업데이트',
    about: '소개',
    faq: 'FAQ',
    menu: '메뉴',
    language: '언어',
    cta: '무료 다운로드',
  },
  hero: {
    badge: '신규',
    announce: 'Lite 버전: 설치 파일이 약 17 MB',
    modes: [
      {
        key: 'capture',
        label: '스크린샷',
        caption: '마우스를 올리면 창과 UI 요소를 자동으로 감지해 원하는 영역을 한 번에 잡습니다.',
      },
      {
        key: 'long',
        label: '스크롤 캡처',
        caption: '긴 페이지와 긴 대화도 자동이든 수동이든 한 장의 이미지로 이어 붙입니다.',
      },
      {
        key: 'pin',
        label: '고정',
        caption: '스크린샷을 화면 맨 위에 띄워 두고 크기와 투명도를 조절하고 나란히 비교합니다.',
      },
      {
        key: 'record',
        label: '녹화',
        caption: '720p부터 4K까지 고프레임 녹화, 커서와 클릭 강조, MP4 또는 GIF 내보내기.',
      },
      { key: 'ai', label: 'AI', caption: 'AI 배경 제거, AI 지우기, 오프라인 OCR — 모두 기기에서 처리합니다.' },
    ],
    h1: [[{ text: '스크린샷, 화면 녹화, ' }, { text: 'AI의 마법', hl: true }], [{ text: '단축키 하나로 모두 해결' }]],
    sub: 'Shotera는 하루에도 수십 번 스크린샷을 찍는 사람을 위한 데스크톱 캡처 도구입니다. 주석 달기, 긴 페이지 스크롤 캡처, GIF 녹화, AI 배경 제거, 오프라인 OCR, 이미지 번역, 바탕 화면에 고정까지 — 작업 흐름을 벗어나지 않고 모두 처리합니다.',
    primary: '무료 다운로드',
    secondary: '사용 방법 보기',
    metaStrong: 'Windows 10/11+',
    metaRest: '설치 버전 / 포터블 버전 / MSI',
    store: 'Microsoft Store에서도 받을 수 있습니다',
    shellMonitor: '알루미늄 모니터 외형',
    shellLaptop: '노트북 외형',
  },
  download: {
    more: '다운로드 옵션 더 보기',
    menu: '다운로드 옵션',
    edition: 'Shotera Standard 버전',
    setup: '설치 버전(.exe)',
    portable: '포터블 버전(.7z)',
    msi: 'MSI 설치 프로그램',
    store: 'Microsoft Store',
    setupTip: '더블 클릭으로 설치합니다. 대부분의 사용자가 선택하는 방식입니다.',
    portableTip: '압축을 풀면 바로 실행됩니다. USB 메모리에 담아 다닐 수 있습니다.',
    msiTip: '주로 기업 관리자가 여러 PC에 일괄 배포할 때 사용합니다.',
    storeTip: 'Microsoft Store에 등록된 버전으로, 스토어에서 앱을 받는 편인 분께 맞습니다.',
    recommend: '추천',
    allVersions: 'GitHub에서 모든 버전 보기',
  },
  trust: [
    { value: '15', label: '지원 언어' },
    { value: '4.9 / 5', label: '사용자 평점' },
    { value: '100%', label: '기기 내 AI 처리' },
    { value: '<0.1s', label: '단축키 실행' },
    {
      value: '{downloads}',
      label: '다운로드',
      badge: '실시간',
      tip: 'GitHub Release 실시간 집계',
    },
  ],
  modesSection: {
    bestFor: '추천 용도',
    eyebrow: '매일 쓰는 세 가지 흐름',
    title: '모든 캡처 작업을 단축키 하나로',
    lead: '스크린샷, 고정, 녹화 & GIF — 하루에도 몇 번씩 찾게 되는 세 가지 작업을 단축키 하나로 끝냅니다.',
    cards: [
      {
        icon: 'capture',
        title: '스크린샷',
        one: '영역, 창, 전체 화면을 키 한 번으로 캡처합니다. 창과 UI 요소는 자동으로 감지합니다.',
        steps: ['단축키 누르기', '마우스를 올려 경계 맞추기', '주석을 달고 복사하거나 저장하기'],
        bestFor: '일상적인 공유와 문서 작업',
      },
      {
        icon: 'pin',
        title: '바탕 화면에 고정',
        one: '스크린샷을 필요한 만큼 화면 맨 위에 띄워 둡니다.',
        steps: ['캡처 직후 바로 고정하기', '크기와 투명도 조절, 나란히 비교', '창을 오가지 않고 작업 이어가기'],
        bestFor: '참고 자료와 나란히 하는 작업',
      },
      {
        icon: 'record',
        title: '화면 녹화 & GIF',
        one: '720p부터 4K까지 30 / 60 프레임으로 녹화하며, 시간 제한이 없습니다.',
        steps: ['영역을 정하고 녹화 시작', '커서와 클릭 표시', 'MP4 또는 GIF로 내보내기'],
        bestFor: '튜토리얼과 버그 리포트',
      },
    ],
  },
  features: [
    {
      eyebrow: '스크린샷',
      title: '한 번의 키로, 정확한 경계까지',
      lead: '단축키로 불러내 캡처와 주석, 복사까지 한 번에 끝냅니다.',
      rows: [
        '마우스를 올리면 아래에 있는 창이나 UI 요소에 Shotera가 자동으로 붙습니다',
        '화살표, 박스, 텍스트, 번호, 이모지, 돋보기 — 캡처한 순간 바로 주석을 답니다',
        '마무리 방식은 두 가지 — 클립보드로 바로 복사하기(우아하고 간결) 또는 주석 도구 모음 바로 열기(바로 주석 달기)',
      ],
      items: [
        { title: '이모지 스티커', note: '클릭 한 번으로 더 풍부한 표현' },
        { title: '돋보기', note: '핵심 디테일 확대' },
        { title: '번호', note: '읽는 순서 안내' },
        { title: '모자이크 & 형광펜', note: '개인정보 보호와 강조' },
      ],
      image: 'capture',
    },
    {
      eyebrow: '스크롤 캡처',
      title: '화면보다 긴 페이지도 한 장으로',
      lead: '긴 페이지, 긴 대화 기록, 문서 전체를 위에서 아래까지 한 장의 이미지로 담습니다.',
      rows: [
        '자동 스크롤, 또는 직접 스크롤 — 진행되는 동안 모든 프레임이 캡처됩니다',
        '인접한 프레임을 맞춰 이어 붙이므로 완성된 긴 이미지에 이음매가 남지 않습니다',
      ],
      items: [
        { title: '이어 붙는 과정을 실시간으로', note: '전체가 담긴 순간 바로 멈추기' },
        { title: '이음매 없는 결과', note: '하나의 연속된 페이지처럼' },
        { title: '긴 대화', note: '대화 전체를 한 장에' },
        { title: '복사하거나 저장', note: '문서와 이슈에 바로 사용' },
      ],
      image: 'longshot',
      reversed: true,
    },
    {
      eyebrow: '고정',
      title: '참고 자료는 위에, 작업은 나란히',
      lead: '스크린샷을 화면 맨 위에 띄워 두고 창을 전환하지 않은 채 비교하고 참고하며 작업합니다.',
      rows: [
        '작업 흐름을 끊지 않고 스크린샷을 화면 맨 위에 고정합니다',
        '가장자리나 모서리를 끌어 크기를 바꾸며 비율은 그대로 유지됩니다. 더블 클릭하면 원본 크기와 썸네일이 전환됩니다',
      ],
      items: [
        { title: '여러 장 동시 고정', note: '나란히 놓고 비교' },
        { title: '썸네일 모드', note: '더블 클릭으로 작게' },
        { title: '마우스 통과', note: '아래 창을 가리지 않음' },
        { title: '마지막 고정 복원', note: '키 한 번으로 다시 표시' },
      ],
      image: 'pin',
    },
    {
      eyebrow: '화면 녹화',
      title: '4K 녹화, 필요한 만큼 오래',
      lead: '“설명하기 어려운” 내용을 누구나 따라 볼 수 있는 클립으로 바꿉니다.',
      rows: [
        '720p / 1080p / 2K / 4K, 30 / 60 프레임, 녹화 시간 제한 없음',
        '가벼운 GIF로 문서와 채팅, 이슈에 바로 붙여 넣습니다 — 플레이어가 필요 없습니다',
      ],
      items: [
        { title: '커서와 클릭 표시', note: '모든 단계가 또렷하게' },
        { title: 'MP4 또는 GIF', note: '화질과 용량을 원하는 대로' },
        { title: '4K 지원', note: '고해상도 디스플레이에 맞춤' },
        { title: '기록', note: '마지막 녹화를 바로 찾기' },
      ],
      image: 'recording',
      reversed: true,
    },
    {
      eyebrow: 'AI 기능',
      title: '스크린샷 마무리는 AI가 맡습니다',
      lead: 'AI 배경 제거, AI 지우기, OCR이 모두 로컬에서 실행됩니다. 프라이버시를 포기하지 않는 똑똑함입니다.',
      rows: [
        '인물, 제품, 로고를 몇 초 만에 투명 PNG로 — 업로드도, 서버 대기 시간도 없습니다',
        'OCR은 기기에서 실행되며 클릭 한 번으로 편집하고 복사할 수 있는 텍스트를 돌려줍니다',
      ],
      items: [
        { title: '피사체 배경 제거', note: '클릭 한 번에 투명 배경' },
        { title: '불필요한 요소 지우기', note: 'AI가 배경을 자연스럽게 복원' },
        { title: '오프라인 OCR', note: '여러 언어 혼용, 코드, 표' },
        { title: '이미지 번역', note: '외국어 스크린샷도 바로 읽기' },
      ],
      image: 'ai',
    },
    {
      eyebrow: '두 가지 완료 모드',
      title: '바로 복사하거나, 그 자리에서 주석 달기',
      lead: '우아하고 간결은 선택을 놓는 순간 클립보드에 복사하고, 바로 주석 달기는 그 자리에서 도구 모음을 엽니다. 언제든 설정 → 캡처에서 바꿀 수 있습니다.',
      rows: [
        '우아하고 간결 — 놓는 순간 복사되고, 오른쪽 아래 알림을 누르면 편집기에서 이어집니다',
        '바로 주석 달기 — 선택과 동시에 도구 모음이 열려 창을 전환하지 않고 주석을 달 수 있습니다',
      ],
      image: 'modes',
      reversed: true,
    },
  ],
  cta: {
    eyebrow: '무료로 시작',
    title: '모든 스크린샷을 더 빠르고 스마트하게',
    lead: '무료로 다운로드하고 몇 초면 설치가 끝납니다. 매일 반복하는 “스크린샷 하나 찍기”는 이 일을 잘 아는 도구에 맡기세요.',
    primary: '무료 다운로드',
    secondary: '다른 버전',
    note: 'Standard 버전과 Lite 버전 제공, Windows 10/11+ 지원. 설치 버전 / 포터블 버전 / MSI를 선택할 수 있습니다.',
  },
  contact: {
    eyebrow: '문의하기',
    title: '질문이나 아이디어가 있으시면 알려 주세요.',
    lead: '문제가 생겼거나, 원하는 기능이 있거나, 그냥 인사를 나누고 싶을 때 — 편한 채널을 골라 주세요.',
    replyNote: '이메일과 GitHub는 매일 확인하며, 보통 영업일 기준 24시간 안에 답변드립니다.',
    faqNote: '막히는 부분이 있나요? 대부분의 답은 이미 FAQ에 있습니다.',
    faqLink: 'FAQ 보기',
    soon: '오픈 예정',
    mail: {
      subject: 'Shotera 피드백 — ',
      body: [
        '안녕하세요,',
        '',
        '(겪으신 문제나 원하시는 기능을 적어 주세요.)',
        '',
        '',
        '가능하시면 아래 정보를 함께 보내 주세요. 더 빠르게 확인할 수 있습니다:',
        '',
        '\u00b7 Shotera 버전(Lite / Standard):',
        '\u00b7 Windows 버전:',
        '\u00b7 문제 재현 방법:',
        '',
        '감사합니다.',
      ].join('\n'),
      copied: '이메일 주소를 복사했습니다 — 메일 앱을 여는 중…',
    },
    groups: [
      {
        key: 'talk',
        title: '직접 연락하기',
        note: '보내 주신 의견은 모두 꼼꼼히 읽습니다.',
        channels: [
          {
            key: 'email',
            name: '이메일',
            handle: 'mosuzo.studio@gmail.com',
            note: '지원, 라이선스, 제휴 문의.',
            icon: 'tabler:mail',
            href: 'mailto:mosuzo.studio@gmail.com',
            tint: '#0a7cff',
          },
          {
            key: 'github',
            name: 'GitHub',
            handle: 'mosuzo-studio/Shotera',
            note: '버그 리포트, 기능 제안, 이전 버전.',
            icon: 'tabler:brand-github',
            href: 'https://github.com/mosuzo-studio/Shotera',
            tint: '#24292f',
          },
          {
            key: 'discord',
            name: 'Discord',
            note: '다른 Shotera 사용자와 대화를 나눠 보세요.',
            icon: 'tabler:brand-discord',
            tint: '#5865f2',
          },
        ],
      },
      {
        key: 'follow',
        title: '소식 받아보기',
        note: '업데이트 소식과 사용 팁, 비하인드 스토리.',
        channels: [
          {
            key: 'x',
            name: 'X',
            note: '업데이트 소식과 짧은 팁.',
            icon: 'tabler:brand-x',
            tint: '#111111',
          },
          {
            key: 'bilibili',
            name: 'Bilibili',
            note: '튜토리얼과 기능 소개 영상.',
            icon: 'tabler:brand-bilibili',
            tint: '#00a1d6',
          },
          {
            key: 'telegram',
            name: 'Telegram',
            note: '새 버전 공지.',
            icon: 'tabler:brand-telegram',
            tint: '#229ed9',
          },
        ],
      },
    ],
  },
  footer: {
    blurb: '더 빠르고 스마트한 스크린샷과 화면 녹화 — 고정하고, 주석 달고, 단축키 하나로 이해까지.',
    cols: [
      {
        title: '제품',
        links: [
          { text: '기능', path: '/', hash: 'features' },
          { text: '버전 비교', path: '/versions' },
        ],
      },
      {
        title: '지원',
        links: [
          { text: 'FAQ', path: '/faq' },
          { text: '업데이트', path: '/changelog' },
        ],
      },
      {
        title: '회사',
        links: [
          { text: '소개', path: '/about' },
          { text: '문의하기', path: '/contact' },
        ],
      },
    ],
    legal: [
      { text: '이용약관', path: '/terms' },
      { text: '개인정보 처리방침', path: '/privacy' },
    ],
    rights: '© 2026 Mosuzo Studio',
    system: 'Windows 10/11+ · 15개 언어 지원',
  },
} satisfies V3LocaleCopy;
