import type { V3LocaleCopy } from './types';

/**
 * Traditional Chinese (Taiwan) copy for the v3 pages. Terminology follows the
 * Shotera app's zh-TW language pack.
 */
export default {
  home: 'Shotera — 更快、更聰明的截圖與錄製螢幕工具',
  nav: {
    features: '功能',
    versions: '版本對比',
    changelog: '更新紀錄',
    about: '關於',
    faq: '常見問題',
    menu: '選單',
    language: '語言',
    cta: '免費下載',
  },
  hero: {
    badge: '新',
    announce: 'Lite 版：安裝檔僅約 17 MB',
    modes: [
      {
        key: 'capture',
        label: '截圖',
        caption: '滑鼠掃過就自動偵測視窗與介面元素，一次就框對要截的範圍。',
      },
      {
        key: 'long',
        label: '長截圖',
        caption: '長網頁、長聊天記錄——自動或手動滾動，拼接成一張長圖。',
      },
      {
        key: 'pin',
        label: '釘在桌面',
        caption: '把截圖釘在螢幕最上層——縮放、半透明、多張並排對照。',
      },
      {
        key: 'record',
        label: '錄製螢幕',
        caption: '720p 到 4K 高影格率錄製，游標與點擊高亮，可匯出 MP4 或 GIF。',
      },
      {
        key: 'ai',
        label: 'AI 能力',
        caption: 'AI 去背、AI 擦除、離線 OCR——全程在裝置上處理。',
      },
    ],
    h1: [[{ text: '截圖、錄製螢幕、' }, { text: 'AI 能力', hl: true }], [{ text: '一個快速鍵全部搞定' }]],
    sub: 'Shotera 是為天天都要截圖的人打造的桌面擷取工具：標註、長截圖、錄製螢幕與 GIF、AI 去背、離線 OCR、圖片翻譯、釘在桌面——不用離開手邊的工作。',
    primary: '免費下載',
    secondary: '看看怎麼用',
    metaStrong: 'Windows 10/11+',
    metaRest: '安裝版 / 免安裝版 / MSI',
    store: '也可在 Microsoft Store 取得',
    shellMonitor: '鋁殼顯示器',
    shellLaptop: '筆電外殼',
  },
  download: {
    more: '更多下載選項',
    menu: '下載選項',
    edition: 'Shotera 標準版',
    setup: '安裝版（.exe）',
    portable: '免安裝版（.7z）',
    msi: 'MSI 安裝程式',
    store: 'Microsoft Store 版',
    setupTip: '雙擊就能安裝，大多數人的選擇。',
    portableTip: '解壓縮就能用，可以放在 USB 隨身碟裡帶著走。',
    msiTip: '通常由企業管理員執行，用來在大量電腦上批次部署。',
    storeTip: '在 Microsoft Store 上架的版本，適合習慣從商店取得應用程式的人。',
    recommend: '推薦',
    allVersions: '所有版本（GitHub）',
  },
  trust: [
    { value: '15 種', label: '介面語言' },
    { value: '4.9 / 5', label: '好評率' },
    { value: '100%', label: '離線 AI 處理' },
    { value: '<0.1s', label: '快速鍵喚起' },
    {
      value: '{downloads}',
      label: '次下載',
      badge: '即時',
      tip: 'GitHub Release 即時下載統計量',
    },
  ],
  modesSection: {
    bestFor: '最適合',
    eyebrow: '日常三件事',
    title: '一個快速鍵，搞定所有截圖任務',
    lead: '截圖、釘在桌面、錄製螢幕與 GIF——每天最常用的三件事，都在同一個快速鍵裡。',
    cards: [
      {
        icon: 'capture',
        title: '截圖',
        one: '一個快速鍵完成區域、視窗或全螢幕截圖，視窗與介面元素都會自動偵測。',
        steps: ['按下快速鍵', '滑鼠掃過，自動框出邊界', '標註、複製或儲存'],
        bestFor: '日常溝通與文件配圖',
      },
      {
        icon: 'pin',
        title: '釘在桌面',
        one: '把截圖釘在所有視窗最上層，想放多久就放多久。',
        steps: ['截圖後直接釘在桌面', '縮放、半透明對照', '邊看邊做，不用切換視窗'],
        bestFor: '對照參考與並排作業',
      },
      {
        icon: 'record',
        title: '錄製螢幕 & GIF',
        one: '720p 到 4K，30 或 60 fps，且無錄製時長限制。',
        steps: ['框選區域開始錄製', '顯示游標與點擊', '匯出 MP4 或 GIF'],
        bestFor: '教學示範與問題回報',
      },
    ],
  },
  features: [
    {
      eyebrow: '截圖',
      title: '一按就到手，邊界剛剛好',
      lead: '快速鍵隨手喚起，截圖、標註、複製一氣呵成，把打斷思緒的操作降到最低。',
      rows: [
        '滑鼠掃過，Shotera 就自動吸附底下的視窗或介面元素',
        '箭頭、方框、文字、編號、Emoji、放大鏡——截完立刻就能標註',
        '兩種完成模式：直接複製到剪貼簿，或立刻開啟標註工具列（優雅簡潔 / 所見即所得）',
      ],
      items: [
        { title: 'Emoji 貼圖', note: '一鍵讓截圖更生動' },
        { title: '放大鏡', note: '局部放大關鍵細節' },
        { title: '編號標註', note: '引導閱讀順序' },
        { title: '馬賽克與螢光筆', note: '隱私與重點兼顧' },
      ],
      image: 'capture',
    },
    {
      eyebrow: '長截圖',
      title: '頁面再長，也一張裝下',
      lead: '長網頁、長聊天記錄、整份文件——從上到下一張截全。',
      rows: ['自動滾動，或自己手動滾，邊滾邊擷取每個畫面', '相鄰畫面自動對齊、融合，拼出的長圖看不出接縫'],
      items: [
        { title: '拼接即時預覽', note: '整頁收進來就停手' },
        { title: '看不出接縫', note: '就像原本的一整頁' },
        { title: '長聊天記錄', note: '整段對話一張裝下' },
        { title: '複製或儲存', note: '直接貼進文件與 Issue' },
      ],
      image: 'longshot',
      reversed: true,
    },
    {
      eyebrow: '釘在桌面',
      title: '參考資料釘在最上層，邊看邊做',
      lead: '把截圖釘在所有視窗最上層——對照、參考，不用切換視窗就能繼續做事。',
      rows: [
        '截圖後直接釘在螢幕最上層，不中斷手邊的操作',
        '從任一邊或角落拖曳縮放，長寬比自動鎖定；雙擊可在原始尺寸與縮圖之間切換',
      ],
      items: [
        { title: '多張並排', note: '幾張參考同時對照' },
        { title: '縮圖模式', note: '雙擊收起，不擋視線' },
        { title: '點擊穿透', note: '不擋住底下的視窗' },
        { title: '一鍵找回', note: '恢復上一次關閉的視窗' },
      ],
      image: 'pin',
    },
    {
      eyebrow: '錄製螢幕',
      title: '4K 錄製，想錄多久就錄多久',
      lead: '把「說不清」的操作，變成一段誰都看得懂的示範影片。',
      rows: [
        '720p / 1080p / 2K / 4K，30 或 60 fps，無錄製時長限制',
        '壓成輕巧的 GIF，貼進文件與 Issue 就能看，不需要播放器',
      ],
      items: [
        { title: '顯示游標與點擊', note: '每一步都看得清楚' },
        { title: 'MP4 或 GIF', note: '畫質與檔案大小，自己取捨' },
        { title: '4K 高畫質', note: '為高解析度螢幕而生' },
        { title: '歷史記錄', note: '隨時找回上一次錄製' },
      ],
      image: 'recording',
      reversed: true,
    },
    {
      eyebrow: 'AI 能力',
      title: 'AI 幫你把截圖收尾',
      lead: 'AI 去背、AI 擦除與 OCR 都在裝置上執行：既聰明，也不必犧牲隱私。',
      rows: [
        '人像、商品、Logo：幾秒鐘就得到透明背景 PNG，不上傳、也不必等伺服器',
        'OCR 在裝置上執行，一鍵取回可編輯、可複製的文字',
      ],
      items: [
        { title: '一鍵去背', note: '點一下就得到透明背景' },
        { title: '擦掉不該出現的東西', note: 'AI 自動補回原本的背景' },
        { title: '離線 OCR', note: '多語混排、程式碼、表格' },
        { title: '圖片翻譯', note: '外文截圖一看就懂' },
      ],
      image: 'ai',
    },
    {
      eyebrow: '兩種完成模式',
      title: '截完即複製，或立刻標註',
      lead: '優雅簡潔：框選完成即複製到剪貼簿；所見即所得：框選完成立刻打開標註工具列。隨時都能在「設定 → 截圖」切換。',
      rows: ['優雅簡潔——框選完成即複製，右下角通知點開進編輯器', '所見即所得——標註工具列隨框選出現，不切換視窗直接畫'],
      image: 'modes',
      reversed: true,
    },
  ],
  cta: {
    eyebrow: '免費開始',
    title: '讓每一次截圖都更快、更聰明',
    lead: '免費下載，幾秒鐘就能裝好。把每天都要做的「截個圖」，交給更懂你的工具。',
    primary: '免費下載',
    secondary: '更多版本',
    note: '提供標準版與 Lite 版；支援 Windows 10/11 以上。安裝版 / 免安裝版 / MSI 都可選用。',
  },
  contact: {
    eyebrow: '聯絡我們',
    title: '有問題或想法？跟我們說。',
    lead: '遇到問題、想要新功能，或只是想聊聊——用你順手的方式找我們。',
    replyNote: '我們每天都會看電子郵件與 GitHub，通常 24 個工作小時內回覆。',
    faqNote: '卡在某個問題上？大部分答案都在常見問題裡了。',
    faqLink: '查看常見問題',
    soon: '即將開放',
    mail: {
      subject: 'Shotera 回饋與建議 — ',
      body: [
        '你好，',
        '',
        '（請描述你遇到的問題，或你希望新增的功能）',
        '',
        '',
        '如果方便，補充以下資訊，可以幫我們更快找到問題：',
        '',
        '· Shotera 版本（Lite 版 / 標準版）：',
        '· Windows 版本：',
        '· 重現步驟：',
        '',
        '謝謝！',
      ].join('\n'),
      copied: '電子郵件已複製，正在開啟郵件應用程式…',
    },
    groups: [
      {
        key: 'talk',
        title: '直接找我們',
        note: '每一則回饋，我們都會仔細讀。',
        channels: [
          {
            key: 'email',
            name: '電子郵件',
            handle: 'mosuzo.studio@gmail.com',
            note: '使用問題、授權、商務合作。',
            icon: 'tabler:mail',
            href: 'mailto:mosuzo.studio@gmail.com',
            tint: '#0a7cff',
          },
          {
            key: 'github',
            name: 'GitHub',
            handle: 'mosuzo-studio/Shotera',
            note: '問題回報、功能建議、歷史版本。',
            icon: 'tabler:brand-github',
            href: 'https://github.com/mosuzo-studio/Shotera',
            tint: '#24292f',
          },
          {
            key: 'discord',
            name: 'Discord',
            note: '和其他 Shotera 使用者交流。',
            icon: 'tabler:brand-discord',
            tint: '#5865f2',
          },
        ],
      },
      {
        key: 'follow',
        title: '關注我們',
        note: '版本消息、使用技巧與幕後花絮。',
        channels: [
          {
            key: 'x',
            name: 'X',
            note: '版本消息與實用技巧。',
            icon: 'tabler:brand-x',
            tint: '#111111',
          },
          {
            key: 'bilibili',
            name: 'Bilibili',
            note: '教學影片與功能示範。',
            icon: 'tabler:brand-bilibili',
            tint: '#00a1d6',
          },
          {
            key: 'telegram',
            name: 'Telegram',
            note: '版本發布公告。',
            icon: 'tabler:brand-telegram',
            tint: '#229ed9',
          },
        ],
      },
    ],
  },
  footer: {
    blurb: '更快、更聰明的截圖與錄製螢幕——釘在桌面、標註、辨識，一個快速鍵就搞定。',
    cols: [
      {
        title: '產品',
        links: [
          { text: '功能', path: '/', hash: 'features' },
          { text: '版本對比', path: '/versions' },
        ],
      },
      {
        title: '支援',
        links: [
          { text: '常見問題', path: '/faq' },
          { text: '更新紀錄', path: '/changelog' },
        ],
      },
      {
        title: '關於',
        links: [
          { text: '關於我們', path: '/about' },
          { text: '聯絡我們', path: '/contact' },
        ],
      },
    ],
    legal: [
      { text: '使用條款', path: '/terms' },
      { text: '隱私權政策', path: '/privacy' },
    ],
    rights: '© 2026 Mosuzo Studio',
    system: 'Windows 10/11+ · 15 種介面語言',
  },
} satisfies V3LocaleCopy;
